### ISSUE TITLE
Running spin pipeline save without a reachable host produces a SIGSEGV

### ISSUE THREAD

**Issue by strideynet** [spinnaker/spin#151]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x146b91a]

goroutine 1 [running]:
github.com/spinnaker/spin/cmd/pipeline.savePipeline(0xc000170c80, 0x195e7b8, 0x0, 0x0, 0x7ffeefbff93a, 0xd, 0x0, 0x0)
        /var/lib/jenkins/workspace/Build_PrimaryArtifacts/build_input/build_spin/src/github.com/spinnaker/spin/cmd/pipeline/save.go:94 +0x2ba
github.com/spinnaker/spin/cmd/pipeline.NewSaveCmd.func1(0xc000170c80, 0xc000112740, 0x0, 0x2, 0x0, 0x0)
        /var/lib/jenkins/workspace/Build_PrimaryArtifacts/build_input/build_spin/src/github.com/spinnaker/spin/cmd/pipeline/save.go:48 +0x49
github.com/spf13/cobra.(*Command).execute(0xc000170c80, 0xc0001126c0, 0x2, 0x2, 0xc000170c80, 0xc0001126c0)
        /var/lib/jenkins/workspace/Build_PrimaryArtifacts/build_input/build_spin/src/github.com/spf13/cobra/command.go:762 +0x473
github.com/spf13/cobra.(*Command).ExecuteC(0xc000139180, 0xc000170280, 0xc000139400, 0xc000114340)
        /var/lib/jenkins/workspace/Build_PrimaryArtifacts/build_input/build_spin/src/github.com/spf13/cobra/command.go:850 +0x2f8
github.com/spf13/cobra.(*Command).Execute(0xc000139180, 0xc00000c018, 0xc000139180)
        /var/lib/jenkins/workspace/Build_PrimaryArtifacts/build_input/build_spin/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/spinnaker/spin/cmd.Execute(0x15fdd00, 0xc00000c018, 0xc0000c7f88, 0x1005320)
        /var/lib/jenkins/workspace/Build_PrimaryArtifacts/build_input/build_spin/src/github.com/spinnaker/spin/cmd/root.go:24 +0x43
main.main()
        /var/lib/jenkins/workspace/Build_PrimaryArtifacts/build_input/build_spin/src/github.com/spinnaker/spin/main.go:26 +0x3d
```

**Comment by jtk54** [comment]
I've seen this before, needs cleaned up.

**Comment by jtk54** [comment]
https://github.com/spinnaker/spin/pull/152
