### ISSUE TITLE
Could not save MPT v2 from spin

### ISSUE THREAD

**Issue by ikemonn** [spinnaker/spin#162]
Hi,
I tried to save MTPv2 at the https://www.spinnaker.io/reference/pipeline/templates/ .
But there were following errors and could not save.
Are there any way to fix this?

## versions
- Spinnaker: v1.13.0 on GKE
- spin: v1.7

## MPT

```json
{
    "schema" : "v2",
    "variables" : [
    {
      "type" : "int",
      "defaultValue" : 10,
      "description" : "description",
      "name" : "waitTime"
    }
    ],
    "id" : "templateName",
    "protect" : false,
    "metadata" : {
      "name" : "displayName", 
      "description" : "description",
      "owner" : "example@example.com",
      "scopes" : ["global"] 
    },
    "pipeline": { 
      "lastModifiedBy" : "anonymous", 
      "updateTs" : "0", 
      "parameterConfig" : [], 
      "limitConcurrent": true,
      "keepWaitingPipelines": false, 
      "description" : "", 
      "triggers" : [],
      "notifications" : [], 
      "stages" : [ 
      {
        "waitTime" : "${ templateVariables.waitTime }", 
        "name": "My Wait Stage",
        "type" : "wait",
        "refId" : "wait1",
        "requisiteStageRefIds": []
      }
      ]
    }
  }
  
```

### spin output

```
➜  spinnaker ./spin pt save --file pt/test.json
Pipeline template save succeeded
➜  spinnaker ./spin pt get --id templateName
Status: 404 , Body: {"body":"{\"timestamp\":1554968289606,\"status\":404,\"error\":\"Not Found\",\"exception\":\"com.netflix.spinnaker.front50.exception.NotFoundException\",\"message\":\"No file at path=front50/pipeline-templates/templatename/specification.json\"}","error":"Not Found","exception":"com.netflix.spinnaker.kork.web.exceptions.GenericExceptionHandlers$RetrofitErrorWrapper","message":"404 ","status":404,"timestamp":1554968289609,"url":"http://spin-front50.evaluation-spinnaker:8080/v2/pipelineTemplates/templateName"}
```

### gate output

```
E0411 16:29:54.817159   84131 portforward.go:316] error copying from local connection to remote stream: read tcp6 [::1]:8084->[::1]:62499: read: connection reset by peer
wwwHandling connection for 8084
```

### orca log

```
2019-04-11 07:25:34.534 ERROR 1 --- [     handlers-7] com.netflix.spinnaker.q.QueueProcessor   : [] Unhandled throwable from CancelStage(executionType=orchestration, executionId=01D85MFB75NFE31VQ0KWXS5N9J, application=global, stageId=01D85MFB77GCQ5M2Z31FDD4133)
com.netflix.spinnaker.orca.pipeline.ExecutionRunner$NoSuchStageDefinitionBuilder: No StageDefinitionBuilder implementation for createV2PipelineTemplate found.  Known stage types: acquireLock,applySourceServerGroupCapacity,bake,bakeManifest,bulkDestroyServerGroup,bulkQuickPatch,bulkUpsertEntityTags,captureSourceServerGroupCapacity,checkPreconditions,cloneServerGroup,copyAmazonLoadBalancer,copyLastAsg,copySecurityGroup,createApplication,createServerGroup,deleteAmazonLoadBalancer,deleteApplication,deleteDeliveryConfig,deleteEntityTags,deleteImage,deleteLoadBalancer,deleteManifest,deleteProject,deleteScalingPolicy,deleteSecurityGroup,deploy,deployCloudFormation,deployManifest,deployService,deregisterInstancesFromLoadBalancer,destroyAsg,destroyJob,destroyServerGroup,destroyService,detachInstances,determineTargetReference,determineTargetServerGroup,disableAsg,disableCluster,disableInstancesInDiscovery,disableManifest,disableServerGroup,enableAsg,enableInstancesInDiscovery,enableManifest,enableServerGroup,evaluateVariables,findArtifactFromExecution,findArtifactsFromResource,findImage,findImageFromTags,jenkins,jira,linearDeploy,manualJudgment,mapLoadBalancers,migrateLoadBalancer,migratePipeline,migrateSecurityGroup,migrateServerGroup,modifyAsg,modifyAsgLaunchConfiguration,modifyAwsScalingProcess,modifyGceAutoscalingPolicy,modifyScalingProcess,noop,pageApplicationOwner,patchManifest,pauseRolloutManifest,pipeline,preconfiguredJob,preconfiguredWebhook,quickPatch,rebootInstances,registerInstancesWithLoadBalancer,releaseLock,reorderPipelines,resizeAsg,resizeServerGroup,restoreSnapshot,restrictExecutionDuringTimeWindow,resumeRolloutManifest,rollbackCluster,rollbackServerGroup,rollingPush,runJob,savePipeline,savePipelinesFromArtifact,saveSnapshot,scaleDownCluster,scaleManifest,script,serverGroupForceCacheRefresh,shareService,shrinkCluster,startAppEngineServerGroup,stopAppEngineServerGroup,terminateInstanceAndDecrementAsg,terminateInstanceAndDecrementServerGroup,terminateInstances,travis,undoRolloutManifest,unmapLoadBalancers,unshareService,updateApplication,updateLaunchConfig,updatePipeline,updateSecurityGroupsForServerGroup,upsertAmazonDNS,upsertAmazonLoadBalancer,upsertAppEngineLoadBalancers,upsertApplication,upsertAsgScheduledActions,upsertAsgTags,upsertDeliveryConfig,upsertEntityTags,upsertImageTags,upsertLoadBalancer,upsertLoadBalancers,upsertProject,upsertScalingPolicy,upsertSecurityGroup,upsertServerGroupTags,wait,waitUntil,webhook,wercker
        at com.netflix.spinnaker.orca.pipeline.DefaultStageDefinitionBuilderFactory.lambda$builderFor$2(DefaultStageDefinitionBuilderFactory.java:48)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at com.netflix.spinnaker.orca.pipeline.DefaultStageDefinitionBuilderFactory.builderFor(DefaultStageDefinitionBuilderFactory.java:46)
        at com.netflix.spinnaker.orca.q.handler.StageBuilderAware$DefaultImpls.builder(StageBuilderAware.kt:28)
        at com.netflix.spinnaker.orca.q.handler.CancelStageHandler.builder(CancelStageHandler.kt:34)
        at com.netflix.spinnaker.orca.q.handler.CancelStageHandler$handle$1.invoke(CancelStageHandler.kt:79)
        at com.netflix.spinnaker.orca.q.handler.CancelStageHandler$handle$1.invoke(CancelStageHandler.kt:34)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:59)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:33)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:68)
        at com.netflix.spinnaker.orca.q.handler.CancelStageHandler.withExecution(CancelStageHandler.kt:34)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:55)
        at com.netflix.spinnaker.orca.q.handler.CancelStageHandler.withStage(CancelStageHandler.kt:34)
        at com.netflix.spinnaker.orca.q.handler.CancelStageHandler.handle(CancelStageHandler.kt:44)
        at com.netflix.spinnaker.orca.q.handler.CancelStageHandler.handle(CancelStageHandler.kt:34)
        at com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)
        at com.netflix.spinnaker.orca.q.handler.CancelStageHandler.invoke(CancelStageHandler.kt:34)
        at com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:47)
        at com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1.run(QueueProcessor.kt:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by jtk54** [comment]
I think you don't have pipeline templates enabled as a feature on your spinnaker deployment. https://github.com/spinnaker/halyard/blob/master/docs/commands.md#hal-config-features-edit.

**Comment by ikemonn** [comment]
OMG 😢 
`hal config features edit --pipeline-templates true` resolved this.
Thank you!
